---
- name: Add Oracle Java 8 PPA
  tags: java
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes
  sudo: true

- name: Automatically select the Oracle License
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  sudo: true

- name: Install Java Packages
  tags: java
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
    - ant
    - maven
