---
- name: Upgrade apt packages
  apt: upgrade=dist update_cache=yes

- name: Install python-software-properties so the apt_repository module will work properly
  apt: pkg=python-software-properties

- name: Remove the unwanted Ack package if it exists
  apt: name=ack state=absent

- name: Install Development Packages
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
    - autoconf
    - build-essential
    - git-core
    - git
    - libreadline6-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libgdbm-dev
    - libncurses5-dev
    - libtool
    - bison
    - libffi-dev
    - libdigest-hmac-perl
    - unzip
    - zlib1g
    - zlib1g-dev
    - libcurl4-openssl-dev
    - curl
    - htop
    - ntp
    - vim
    - ack-grep
    - bash-completion
